### ISSUE TITLE
Add a "install_on_mac.md" Onboarding Document

### ISSUE THREAD

**Issue by VladimirKupryukhin** [TrickfireRobotics/urc-2023#22]
Create a document under `/docs` in order for Mac users to follow in order to setup their work environment. 

The general rule of thumb is to have them install Docker, Git, and this repository. Make sure to mention the issue with M1 chips and Docker. Make sure to add references to this document in the `getting_started.md` document.

**Comment by ezekielmitchell** [comment]
I'll tackle this tonight/early tomorrow morning.

**Comment by ezekielmitchell** [comment]
completed - pending merge*
